services:
  profilarr:
    image: ghcr.io/dictionarry-hub/profilarr:latest
    container_name: profilarr
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    ports:
      - "100.64.0.1:6868:6868"
    volumes:
      - config:/config

volumes:
  config:
