services:
  authelia:
    image: authelia/authelia:4.39.20
    container_name: authelia
    restart: unless-stopped
    env_file: .env
    command:
      - 'authelia'
      - '--config=/config/configuration.yml'
      - '--config=/config/oidc.yml'
    ports:
      - "127.0.0.1:9091:9091"
    volumes:
      - authelia-data:/config
      - ./configuration.yml:/config/configuration.yml:ro
      - ./users_database.yml:/config/users_database.yml:ro
      - ./oidc.yml:/config/oidc.yml:ro

volumes:
  authelia-data:
