#ENC[AES256_GCM,data:+FnO9SMbpikYa/+dULML0iPOQJz5xAMQdANg4rYybU9kh59yqmt2vUShHj8E1o4Xlqj+udcsOAwv/J/XSiKBBKlwFkViuV+qQ8hoUpQ+BNt5WJ9+Jk+kJRyj0gmmEvBsTRlb4g==,iv:Ut9DKoTddDAoSRRQCHphvmf50NdddhPCzlqDN1F7D58=,tag:BCDRtV1wSohrYpiSET5jXw==,type:comment]
totp:
    issuer: ENC[AES256_GCM,data:LcRVVHCtHp9tMVTCvHPn,iv:brRA54AR51qLC5JWPoKudJHcZDsPzHMCc8rl7Smbhd4=,tag:9gMZZCN7hGEm14/UBTIcpg==,type:str]
authentication_backend:
    file:
        path: ENC[AES256_GCM,data:lmcWL2KW6I3jgjElf8KzsH7208yUVITbFbE=,iv:TUDiadMjF84V4nyPih4B6Hwd4AvseakB6xfFB5oiWI0=,tag:2EAiylN4zeCaD9/5omBhEA==,type:str]
access_control:
    default_policy: ENC[AES256_GCM,data:l18gamy/Z4fbnw==,iv:LZkyfv9MCJYDXMcpGaiRv5RWRVaRLETvVikWvQ3frZo=,tag:fL1NIl9w85JAKA/11V45oQ==,type:str]
session:
    cookies:
        - domain: ENC[AES256_GCM,data:0zl+Jgi2ZAD5AA89BS+M,iv:5OKvXJz/jk8cSOreJXrcVwy9YBMSlAF5ejEJCPQGTAE=,tag:6TXR6fk4lRq8sVRb9UsiDA==,type:str]
          authelia_url: ENC[AES256_GCM,data:CP4abu02UhOYO0iMYbHzosOlFWtmp9m8It4D2g==,iv:WooTCitDGsvTrETMPjYRZQn/meum7+E/SUFSxjdWfGU=,tag:PWAZBtNwr0FSbCI9Dc8G2Q==,type:str]
          default_redirection_url: ENC[AES256_GCM,data:5qfv7REAOUBSD2o6AsYnc0yHlsCP2gWoYWgzjA==,iv:T1A2y4bhl3ClvK+Drjrb80y0ig4kzvtr6sl00naFquM=,tag:ZlLWYoxTvgihpiRJxjWWGA==,type:str]
storage:
    local:
        path: ENC[AES256_GCM,data:wj1zl50gE2Plu93h0iDC8sq6,iv:CL/1O/g2j1f5eOhUBWD38urpJNPWFDcUcDCDGIHsAto=,tag:PDQdjkpjZJMp+BEnTJHQQw==,type:str]
notifier:
    filesystem:
        filename: ENC[AES256_GCM,data:hbfLAcnnJSSDbIJr4Ci47qDECyYWOZBe,iv:agIOpcjC0mCY1WL2PzDmwOtsYzy0Nxk8Ok2esPjxDEI=,tag:cSHS9YQmPReC2LCIXUeV3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bkR6eFV5emVDbjZ6c05X
            cTRuMkNUWjdSUUJYUVE5eXFTWmduZkhQaW5RCnVnOEtTMUdpUkVKR0JmVm0vanlO
            M0RaMEhGWUc5K1ZlSlZRdHBYRWFZbW8KLS0tIHBPeFM2U0RRaDJyZjRCQUVpeUVR
            dktoSk80M1dnU005QWNVVTAxekxXNFEKq171/K02I4qf/5NznjUZ1+WCguz9isbR
            KlCkXTdqGnkkFqjkS0ES84OH5HJiIwBgUx2WJwpOSMwLC0sZHzJLgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wce7sqneyq58tux6fnpj2e2tsc05j4jqk8h8dguu0jc6eplfrslqqdw7md
    lastmodified: "2026-07-23T17:41:32Z"
    mac: ENC[AES256_GCM,data:z6sYGNAaVXKbwMPV04DRdeaqe4ihh5XxfzuuV+uVjxoTRNm+LN1swnX0c0gn2rwKBhKUhPCkV9/Gopo1SCm1vASJlHVJOm1rlfc2APkgwKxlojyMn+S7AtpPwxC1/7pdpyd/40oXQj1V4JqZzd+UClYVbAWRO7z/g/CPTccW4hc=,iv:fyLL2i225n59hJ9u+AmzxL3/NpI2bIXXp45WGsaDdko=,tag:+3WWnpXMgo6/F1tUMMJG3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
